# Generated by Django 3.1.4 on 2021-08-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttopics',
            name='self_proposed',
            field=models.CharField(choices=[('c', 'Confirmed'), ('d', 'Denied')], default='pending', max_length=1),
        ),
    ]
