# Generated by Django 3.1.4 on 2021-08-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_projecttopics_self_proposed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttopics',
            name='self_proposed',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Confirmed'), ('d', 'Denied')], default='pending', max_length=1),
        ),
    ]
