# Generated by Django 3.1.4 on 2021-08-04 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210803_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttopics',
            name='topic_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
