# Generated by Django 3.1.4 on 2021-08-04 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20210804_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttopics',
            name='topic_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
