# Generated by Django 3.1.4 on 2021-08-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_auto_20210804_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttopics',
            name='topic_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
